name: scrape-daily

on:
  schedule:
    # 05:00 UTC ≈ 06:00 (sommar) / 07:00 (vinter) i Sverige
    - cron: "0 4 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python (with pip cache)
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: pw-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pw-${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m playwright install chromium

      - name: Kör alla scripts
        run: |
          set +e
          declare -A rc
          declare -A outputs

          echo " "
          outputs[eql_find]="$(python -u -m scripts.eql_find 2>&1)"; rc[eql_find]=$?
          echo "${outputs[eql_find]}"

          echo " "
          outputs[adtraction_stats]="$(python -u -m scripts.adtraction_stats 2>&1)"; rc[adtraction_stats]=$?
          echo "${outputs[adtraction_stats]}"

          echo " "
          outputs[adtraction_epc_finance]="$(python -u -m scripts.adtraction_epc_finance 2>&1)"; rc[adtraction_epc_finance]=$?
          echo "${outputs[adtraction_epc_finance]}"

          echo " "
          outputs[rugvista_aov]="$(python -u -m scripts.rugvista_aov 2>&1)"; rc[rugvista_aov]=$?
          echo "${outputs[rugvista_aov]}"

          echo " "
          outputs[soder_stats]="$(python -u -m scripts.soder_stats 2>&1)"; rc[soder_stats]=$?
          echo "${outputs[soder_stats]}"

          echo " "
          outputs[soder_ads]="$(python -u -m scripts.soder_ads 2>&1)"; rc[soder_ads]=$?
          echo "${outputs[soder_ads]}"

          # echo " "
          # outputs[fractal_refine]="$(python -u -m scripts.fractal_refine 2>&1)"; rc[fractal_refine]=$?
          # echo "${outputs[fractal_refine]}"

          # echo " "
          # outputs[fractal_scape]="$(python -u -m scripts.fractal_scape 2>&1)"; rc[fractal_scape]=$?
          # echo "${outputs[fractal_scape]}"

          echo " "
          outputs[sitemap_fetch]="$(python -u -m scripts.sitemap_fetch 2>&1)"; rc[sitemap_fetch]=$?
          echo "${outputs[sitemap_fetch]}"


          {
            echo "## Daglig scraping – summering"
            echo ""
            echo "| Script | Status | Output |"
            echo "|-------:|:-------|:-------|"

            scripts=(
              "eql_find"
              "adtraction_stats"
              "adtraction_epc_finance"
              "rugvista_aov"
              "soder_stats"
              "soder_impressions"
              # "fractal_refine"
              # "fractal_scape"
              "sitemap_fetch"
            )

            for k in "${scripts[@]}"; do
              out="${outputs[$k]}"
              # Escapa tabelltecken/nyrader för GitHub-markdown
              out="${out//|/\\|}"
              out="${out//$'\r'/}"           # ta bort CR om sådana finns
              out="${out//$'\n'/<br/>}"
              if [[ "${rc[$k]}" -eq 0 ]]; then st="✅ OK"; else st="❌ FAIL (${rc[$k]})"; fi
              printf "| \`%s\` | %s | %s |\n" "$k" "$st" "$out"
            done
          } >> "$GITHUB_STEP_SUMMARY"

          exit 0

      - name: Lägg till backup-filer i ./history
        if: always()
        run: |
          mkdir -p history
          TODAY=$(date +%Y-%m-%d)
          MODIFIED=$(git diff --name-only HEAD -- data/*.xlsx || true)
          NEW=$(git ls-files --others --exclude-standard -- data/*.xlsx || true)
          for f in $MODIFIED $NEW; do
            [ -f "$f" ] || continue
            base=$(basename "$f")
            dest="history/backup_${TODAY}_$base"
            cp "$f" "$dest"
            echo "Backup: $f -> $dest"
          done

      - name: Commita & pusha uppdaterade filer
        if: always()
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/*.xlsx || true
          git add history/backup_*.xlsx || true
          if git diff --cached --quiet; then
            echo "Inga ändringar att committa."
            exit 0
          fi
          git commit -m "chore: update data files + selective backups [skip ci]"
          git push origin HEAD:${GITHUB_REF_NAME:-main}
