name: scrape-daily

on:
  schedule:
    - cron: "0 4 * * *"   # 07:00 SE (GitHub Actions kör i UTC)
  workflow_dispatch:

permissions:
  contents: write  # krävs för att pusha med GITHUB_TOKEN

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Om du använder Playwright i något script:
          python -m playwright install chromium
          python -m playwright install-deps || true

      - name: Run all scripts (module mode; never stop on error)
        run: |
          set +e
          declare -A rc

          echo "=== Running run_monthly.py ==="
          python -u run_monthly.py; rc[run_monthly]=$?

          echo "=== Running scripts/adtraction_epc_finance.py ==="
          python -u -m scripts.adtraction_epc_finance; rc[adtraction_epc_finance]=$?

          echo "=== Running scripts/adtraction_epc_all.py ==="
          python -u -m scripts.adtraction_epc_all; rc[adtraction_epc_all]=$?

          echo "=== Running scripts/adtraction_stats.py ==="
          python -u -m scripts.adtraction_stats; rc[adtraction_stats]=$?

          echo "=== Running scripts/fractal_refine.py ==="
          python -u -m scripts.fractal_refine; rc[fractal_refine]=$?

          echo "=== Running scripts/fractal_scape.py ==="
          python -u -m scripts.fractal_scape; rc[fractal_scape]=$?

          echo "=== Running scripts/fractal_headset_inet.py ==="
          python -u -m scripts.fractal_headset_inet; rc[fractal_headset_inet]=$?

          echo "=== Running scripts/fractal_trends.py ==="
          python -u -m scripts.fractal_trends; rc[fractal_trends]=$?

          echo "=== Running scripts/rugvista_aov.py ==="
          python -u -m scripts.rugvista_aov; rc[rugvista_aov]=$?

          echo "=== Running scripts/rugvista_trends.py ==="
          python -u -m scripts.rugvista_trends; rc[rugvista_trends]=$?

          echo "=== Running scripts/soder_stats.py ==="
          python -u -m scripts.soder_stats; rc[soder_stats]=$?

          echo "=== Running scripts/soder_trends.py ==="
          python -u -m scripts.soder_trends; rc[soder_trends]=$?

          mkdir -p history
          printf "script,status\n" > history/run_status.csv
          for k in "${!rc[@]}"; do
            if [ "${rc[$k]}" -eq 0 ]; then st="OK"; else st="FAIL(${rc[$k]})"; fi
            printf "%s,%s\n" "$k" "$st" >> history/run_status.csv
          done

          {
            echo "## Daglig scraping – summering"
            echo ""
            echo "| Script | Status |"
            echo "|-------:|:-------|"
            for k in "${!rc[@]}"; do
              if [ "${rc[$k]}" -eq 0 ]; then st="✅ OK"; else st="❌ FAIL (${rc[$k]})"; fi
              echo "| \`$k\` | $st |"
            done
          } >> "$GITHUB_STEP_SUMMARY"

          exit 0

      # ⬇️ NYTT: backa upp ENDAST ändrade/nya xlsx i data/
      - name: Backup updated XLSX files to history
        if: always()
        run: |
          mkdir -p history
          TODAY=$(date +%Y-%m-%d)
          # Ändrade (tracked) filer sedan HEAD
          MODIFIED=$(git diff --name-only HEAD -- data/*.xlsx || true)
          # Nya (untracked) filer
          NEW=$(git ls-files --others --exclude-standard -- data/*.xlsx || true)
          for f in $MODIFIED $NEW; do
            [ -f "$f" ] || continue
            base=$(basename "$f")
            dest="history/backup_${TODAY}_$base"
            cp "$f" "$dest"
            echo "Backup: $f -> $dest"
          done

      - name: Commit & push updated files (if any)
        if: always()
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Lägg till Excel i data/, run-logg och backuper
          git add data/*.xlsx || true
          git add history/*.csv || t*
