name: scrape-daily

on:
  schedule:
    - cron: "17-29/3 14 * * *"  # var 3:e minut från 14:17 till 14:29 UTC (16:17–16:29 CEST)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  adtraction:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run scraper
        run: python adtraction_stats.py
