name: scrape-daily

on:
  schedule:
    - cron: "0 5 * * *"   # 07:00 SE (05:00 UTC sommartid)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run adtraction_stats.py
        run: python adtraction_stats.py
        continue-on-error: true

      - name: Run fractal_headset.py
        run: python fractal_headset.py
        continue-on-error: true

      - name: Run fractal_refine.py
        run: python fractal_refine.py
        continue-on-error: true

      - name: Run soder_stats.py
        run: python soder_stats.py
        continue-on-error: true
