name: scrape-daily

on:
  schedule:
    - cron: "0 5 * * *"  # 07:00 CEST
  workflow_dispatch:

jobs:
  adtraction:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 openpyxl

      - name: Run scraper
        run: python jobs/adtraction_stats.py

      - name: Commit changes (if any)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(data): update ADTR_conversions"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          file_pattern: data/rådata.xlsx
